# Generated by Django 3.2.15 on 2023-05-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_mangapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover_image',
            field=models.ImageField(upload_to='media/covers'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='image',
            field=models.ImageField(upload_to='media/manga_pages'),
        ),
    ]
